src/java/com/sipre/controlador/BiContratoproveedorController.java
package com.sipre.controlador;

import com.sipre.entidad.BiContratoproveedor;
import com.sipre.controlador.util.JsfUtil;
import com.sipre.controlador.util.PaginationHelper;
import com.sipre.facades.BiContratoproveedorFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("biContratoproveedorController")
@SessionScoped
public class BiContratoproveedorController implements Serializable {

    private BiContratoproveedor current;
    private DataModel items = null;
    @EJB
    private com.sipre.facades.BiContratoproveedorFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public BiContratoproveedorController() {
    }

    public BiContratoproveedor getSelected() {
        if (current == null) {
            current = new BiContratoproveedor();
            selectedItemIndex = -1;
        }
        return current;
    }

    private BiContratoproveedorFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (BiContratoproveedor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new BiContratoproveedor();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("Parametros/parametro").getString("BiContratoproveedorCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("Parametros/parametro").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (BiContratoproveedor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("Parametros/parametro").getString("BiContratoproveedorUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("Parametros/parametro").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (BiContratoproveedor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("Parametros/parametro").getString("BiContratoproveedorDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("Parametros/parametro").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public BiContratoproveedor getBiContratoproveedor(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = BiContratoproveedor.class)
    public static class BiContratoproveedorControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            BiContratoproveedorController controller = (BiContratoproveedorController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "biContratoproveedorController");
            return controller.getBiContratoproveedor(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof BiContratoproveedor) {
                BiContratoproveedor o = (BiContratoproveedor) object;
                return getStringKey(o.getCodContrato());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + BiContratoproveedor.class.getName());
            }
        }

    }

}

web/app/biContratoproveedor/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametro.CreateBiContratoproveedorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="4">
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_codContrato}" for="codContrato" />
                    <h:inputText id="codContrato" value="#{biContratoproveedorController.selected.codContrato}" title="#{parametro.CreateBiContratoproveedorTitle_codContrato}" required="true" requiredMessage="#{parametro.CreateBiContratoproveedorRequiredMessage_codContrato}"/>
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_numContrato}" for="numContrato" />
                    <h:inputText id="numContrato" value="#{biContratoproveedorController.selected.numContrato}" title="#{parametro.CreateBiContratoproveedorTitle_numContrato}" />
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_actUsuario}" for="actUsuario" />
                    <h:inputText id="actUsuario" value="#{biContratoproveedorController.selected.actUsuario}" title="#{parametro.CreateBiContratoproveedorTitle_actUsuario}" />
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_estActividad}" for="estActividad" />
                    <h:inputText id="estActividad" value="#{biContratoproveedorController.selected.estActividad}" title="#{parametro.CreateBiContratoproveedorTitle_estActividad}" />
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_horActividad}" for="horActividad" />
                    <h:inputText id="horActividad" value="#{biContratoproveedorController.selected.horActividad}" title="#{parametro.CreateBiContratoproveedorTitle_horActividad}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{parametro.CreateBiContratoproveedorLabel_codProveedor}" for="codProveedor" />
                    <h:selectOneMenu id="codProveedor" value="#{biContratoproveedorController.selected.codProveedor}" title="#{parametro.CreateBiContratoproveedorTitle_codProveedor}" >
                        <f:selectItems value="#{biTerceroController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{biContratoproveedorController.create}" value="#{parametro.CreateBiContratoproveedorSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{biContratoproveedorController.prepareList}" value="#{parametro.CreateBiContratoproveedorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametro.CreateBiContratoproveedorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/app/biContratoproveedor/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametro.EditBiContratoproveedorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="4">
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_codContrato}" for="codContrato" />
                    <h:inputText id="codContrato" value="#{biContratoproveedorController.selected.codContrato}" title="#{parametro.EditBiContratoproveedorTitle_codContrato}" required="true" requiredMessage="#{parametro.EditBiContratoproveedorRequiredMessage_codContrato}"/>
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_numContrato}" for="numContrato" />
                    <h:inputText id="numContrato" value="#{biContratoproveedorController.selected.numContrato}" title="#{parametro.EditBiContratoproveedorTitle_numContrato}" />
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_actUsuario}" for="actUsuario" />
                    <h:inputText id="actUsuario" value="#{biContratoproveedorController.selected.actUsuario}" title="#{parametro.EditBiContratoproveedorTitle_actUsuario}" />
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_estActividad}" for="estActividad" />
                    <h:inputText id="estActividad" value="#{biContratoproveedorController.selected.estActividad}" title="#{parametro.EditBiContratoproveedorTitle_estActividad}" />
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_horActividad}" for="horActividad" />
                    <h:inputText id="horActividad" value="#{biContratoproveedorController.selected.horActividad}" title="#{parametro.EditBiContratoproveedorTitle_horActividad}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{parametro.EditBiContratoproveedorLabel_codProveedor}" for="codProveedor" />
                    <h:selectOneMenu id="codProveedor" value="#{biContratoproveedorController.selected.codProveedor}" title="#{parametro.EditBiContratoproveedorTitle_codProveedor}" >
                        <f:selectItems value="#{biTerceroController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{biContratoproveedorController.update}" value="#{parametro.EditBiContratoproveedorSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{parametro.EditBiContratoproveedorViewLink}"/>
                <br />
                <h:commandLink action="#{biContratoproveedorController.prepareList}" value="#{parametro.EditBiContratoproveedorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametro.EditBiContratoproveedorIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/app/biContratoproveedor/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametro.ListBiContratoproveedorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{parametro.ListBiContratoproveedorEmpty}" rendered="#{biContratoproveedorController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{biContratoproveedorController.items.rowCount > 0}">
                    <h:outputText value="#{biContratoproveedorController.pagination.pageFirstItem + 1}..#{biContratoproveedorController.pagination.pageLastItem + 1}/#{biContratoproveedorController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{biContratoproveedorController.previous}" value="#{parametro.Previous} #{biContratoproveedorController.pagination.pageSize}" rendered="#{biContratoproveedorController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{biContratoproveedorController.next}" value="#{parametro.Next} #{biContratoproveedorController.pagination.pageSize}" rendered="#{biContratoproveedorController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{biContratoproveedorController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_codContrato}"/>
                            </f:facet>
                            <h:outputText value="#{item.codContrato}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_numContrato}"/>
                            </f:facet>
                            <h:outputText value="#{item.numContrato}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_actUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.actUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_estActividad}"/>
                            </f:facet>
                            <h:outputText value="#{item.estActividad}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_horActividad}"/>
                            </f:facet>
                            <h:outputText value="#{item.horActividad}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{parametro.ListBiContratoproveedorTitle_codProveedor}"/>
                            </f:facet>
                            <h:outputText value="#{item.codProveedor}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{biContratoproveedorController.prepareView}" value="#{parametro.ListBiContratoproveedorViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{biContratoproveedorController.prepareEdit}" value="#{parametro.ListBiContratoproveedorEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{biContratoproveedorController.destroy}" value="#{parametro.ListBiContratoproveedorDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{biContratoproveedorController.prepareCreate}" value="#{parametro.ListBiContratoproveedorCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametro.ListBiContratoproveedorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/app/biContratoproveedor/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{parametro.ViewBiContratoproveedorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="4">
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_codContrato}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.codContrato}" title="#{parametro.ViewBiContratoproveedorTitle_codContrato}"/>
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_numContrato}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.numContrato}" title="#{parametro.ViewBiContratoproveedorTitle_numContrato}"/>
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_actUsuario}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.actUsuario}" title="#{parametro.ViewBiContratoproveedorTitle_actUsuario}"/>
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_estActividad}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.estActividad}" title="#{parametro.ViewBiContratoproveedorTitle_estActividad}"/>
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_horActividad}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.horActividad}" title="#{parametro.ViewBiContratoproveedorTitle_horActividad}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{parametro.ViewBiContratoproveedorLabel_codProveedor}"/>
                    <h:outputText value="#{biContratoproveedorController.selected.codProveedor}" title="#{parametro.ViewBiContratoproveedorTitle_codProveedor}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{biContratoproveedorController.destroyAndView}" value="#{parametro.ViewBiContratoproveedorDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{parametro.ViewBiContratoproveedorEditLink}"/>
                <br />
                <h:commandLink action="#{biContratoproveedorController.prepareCreate}" value="#{parametro.ViewBiContratoproveedorCreateLink}" />
                <br />
                <h:commandLink action="#{biContratoproveedorController.prepareList}" value="#{parametro.ViewBiContratoproveedorShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{parametro.ViewBiContratoproveedorIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>